package org.HEI.kdot;

public enum MovieType {
    COMEDIE, ROMANCE, THRILLER, ACTION, ANIMATION, SITCOM, FANTASY, SCIFI, MYSTERY, ANIME, CARTOON, RETRO, WESTERN, HISTORICAL, HISTORY, DOCUMENTARY, POLICE, WAR, MILITARY,BIOPIC, SPORT, CAR
}
